; Generated by build/Build-Installer.ps1
#define MyAppName      "BCFier SP"
#define MyAppVersion   "1.0.16"
#define MyAppPublisher "SmartProject"
#define MyAppExeName   "BCFier.Win.exe"

[Setup]
AppId={{A3C8E2F1-9B4D-4F7A-8C1E-2D5B6A9F0E31}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={localappdata}\BCFier-SP
DisableDirPage=yes
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
DisableWelcomePage=no
OutputDir=C:\Users\Kanuhin_A\source\repos\SP\SP-BCFier\dist
OutputBaseFilename=BCFier-SP-{#MyAppVersion}-Setup
SetupIconFile=C:\Users\Kanuhin_A\source\repos\SP\SP-BCFier\Assets\icon.ico
Compression=lzma
SolidCompression=yes
WizardImageFile=C:\Users\Kanuhin_A\source\repos\SP\SP-BCFier\Assets\bcfier-banner.bmp
PrivilegesRequired=lowest
UninstallDisplayIcon={app}\icon.ico
ArchitecturesInstallIn64BitMode=x64compatible

[Languages]
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"
Name: "english"; MessagesFile: "compiler:Default.isl"

[Types]
Name: "full"; Description: "Полная установка / Full install"
Name: "custom"; Description: "Выборочная / Custom"; Flags: iscustom

[Components]
Name: "revit2022"; Description: "Add-in for Autodesk Revit 2022"; Types: full custom
Name: "revit2023"; Description: "Add-in for Autodesk Revit 2023"; Types: full custom
Name: "revit2025"; Description: "Add-in for Autodesk Revit 2025"; Types: full custom
Name: "revit2026"; Description: "Add-in for Autodesk Revit 2026"; Types: full custom
Name: "standalone"; Description: "BCFier for Windows (просмотр BCF без Revit)"; Types: full custom

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; Components: standalone

[Files]
Source: "C:\Users\Kanuhin_A\source\repos\SP\SP-BCFier\Assets\icon.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Kanuhin_A\source\repos\SP\SP-BCFier\dist\R2022\*"; DestDir: "{userappdata}\Autodesk\Revit\Addins\2022"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: revit2022; Excludes: "README.txt,Install-Standalone.ps1"
Source: "C:\Users\Kanuhin_A\source\repos\SP\SP-BCFier\dist\R2023\*"; DestDir: "{userappdata}\Autodesk\Revit\Addins\2023"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: revit2023; Excludes: "README.txt,Install-Standalone.ps1"
Source: "C:\Users\Kanuhin_A\source\repos\SP\SP-BCFier\dist\R2025\*"; DestDir: "{userappdata}\Autodesk\Revit\Addins\2025"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: revit2025; Excludes: "README.txt,Install-Standalone.ps1"
Source: "C:\Users\Kanuhin_A\source\repos\SP\SP-BCFier\dist\R2026\*"; DestDir: "{userappdata}\Autodesk\Revit\Addins\2026"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: revit2026; Excludes: "README.txt,Install-Standalone.ps1"
Source: "C:\Users\Kanuhin_A\source\repos\SP\SP-BCFier\dist\Win\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: standalone; Excludes: "*.pdb"

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Components: standalone
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon; Components: standalone

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent; Components: standalone
